export const bate = 'beta'
export const newVersionBeta = `0.0.1-${bate}.1`
export const newVersion = '1.0.0'
export const addVersion = '1.1.0'
export const changePackagesFile = 'packages/a/test'
export const changePackagesFile2 = 'packages/b/test'
export const changeRootFile = 'test'
export const quarantineNotTest = 'quarantineNotTest'
export const quarantine = 'quarantine'
export const many = 'many'
export const Interdependence = 'Interdependence'
export const single = 'single'
export const ORIGINAL_CWD = process.cwd()
export const dirQuarantineNotTestArr = ['a']
export const dirQuarantineNotTestCommandOrder = ['a']
export const dirQuarantineNotTestCommandOrderChange1 = ['a']
export const dirQuarantineArr = ['a', 'b']
export const dirQuarantineCommandOrder = ['a', 'b']
export const dirQuarantineCommandOrderChange1 = ['a']
export const dirQuarantineCommandOrderChange2 = ['b']
export const dirManyArr = ['a', 'b', 'c', 'd', 'e']
export const dirManyCommandOrder = ['a', 'b', 'd', 'e', 'c']
export const dirManyCommandOrderChange1 = ['a', 'b', 'e']
export const dirManyCommandOrderChange2 = ['b']
export const dirInterdependenceArr = ['a', 'b', 'c']
export const dirInterdependenceArrDiff = ['a', 'c', 'b']
export const dirInterdependenceCommandOrder = ['a', 'c']
export const dirInterdependenceCommandOrderChange1 = ['b', 'a']
export const rootPackageJsonArr = ['root']
