export const bate = 'beta'
export const newVersionBeta = `0.0.1-${bate}.1`
export const newVersion = '1.0.0'
export const addVersion = '1.1.0'
export const quarantine = 'quarantine'
export const many = 'many'
export const Interdependence = 'Interdependence'
export const ORIGINAL_CWD = process.cwd()
export const dirQuarantineArr = ['a', 'b']
export const dirManyArr = ['a', 'b', 'c', 'd', 'e']
export const dirInterdependenceArr = ['a', 'b', 'c']
